<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerB38D3fa\Shrikeh_SymfonyKernel_DefaultKernelFooContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerB38D3fa/Shrikeh_SymfonyKernel_DefaultKernelFooContainer.php') {
    touch(__DIR__.'/ContainerB38D3fa.legacy');

    return;
}

if (!\class_exists(Shrikeh_SymfonyKernel_DefaultKernelFooContainer::class, false)) {
    \class_alias(\ContainerB38D3fa\Shrikeh_SymfonyKernel_DefaultKernelFooContainer::class, Shrikeh_SymfonyKernel_DefaultKernelFooContainer::class, false);
}

return new \ContainerB38D3fa\Shrikeh_SymfonyKernel_DefaultKernelFooContainer([
    'container.build_hash' => 'B38D3fa',
    'container.build_id' => '4759dfaa',
    'container.build_time' => 1590162308,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerB38D3fa');
