<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMJdZRhW\Shrikeh_SymfonyKernel_DefaultKernelTestContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMJdZRhW/Shrikeh_SymfonyKernel_DefaultKernelTestContainer.php') {
    touch(__DIR__.'/ContainerMJdZRhW.legacy');

    return;
}

if (!\class_exists(Shrikeh_SymfonyKernel_DefaultKernelTestContainer::class, false)) {
    \class_alias(\ContainerMJdZRhW\Shrikeh_SymfonyKernel_DefaultKernelTestContainer::class, Shrikeh_SymfonyKernel_DefaultKernelTestContainer::class, false);
}

return new \ContainerMJdZRhW\Shrikeh_SymfonyKernel_DefaultKernelTestContainer([
    'container.build_hash' => 'MJdZRhW',
    'container.build_id' => 'ed7598fa',
    'container.build_time' => 1590162329,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMJdZRhW');
